# Generated by Django 4.0.3 on 2022-04-11 14:24

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('response_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=200)),
                ('mobile', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('location_type', models.CharField(choices=[('Casa', 'Casa'), ('Escritório', 'Escritório'), ('Apartamento', 'Apartamento')], max_length=20)),
                ('area_m2', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
                ('qty_bedroom', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=2)),
                ('qty_living', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=2)),
                ('qty_bathroom', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=2)),
                ('window', models.BooleanField()),
                ('qty_window', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=2)),
                ('kitchen', models.BooleanField()),
                ('kitchen_addon', models.CharField(choices=[('Microondas', 'Microondas'), ('Frigorífico', 'Frigorífico'), ('Forno', 'Forno')], max_length=50)),
                ('bedroom_addon', models.CharField(choices=[(1, 'Limpeza do chão'), (2, 'Organização dos Armários'), (3, 'Troca de Roupa de Cama')], max_length=50)),
                ('living_addon', models.CharField(choices=[(1, 'Tirar pó dos armários'), (2, 'Limpeza interna dos armários'), (3, 'Limpeza de pia e box')], max_length=100)),
                ('last_clean', models.BooleanField(default=True)),
                ('pets', models.BooleanField()),
                ('best_day', models.CharField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], max_length=50)),
                ('best_time', models.CharField(choices=[('morning', 'morning'), ('afternoon', 'afternoon')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
