# Generated by Django 4.0.3 on 2022-04-11 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='mobile',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +999999999. Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='qty_bathroom',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=2),
        ),
        migrations.AlterField(
            model_name='quote',
            name='qty_bedroom',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=2),
        ),
        migrations.AlterField(
            model_name='quote',
            name='qty_living',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=2),
        ),
        migrations.AlterField(
            model_name='quote',
            name='qty_window',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=2),
        ),
    ]
