# Generated by Django 4.0.3 on 2022-04-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getservice', '0003_alter_quote_qty_bathroom_alter_quote_qty_bedroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='bedroom_addon',
            field=models.CharField(choices=[('a', 'Limpeza do chão'), ('b', 'Organização dos Armários'), ('c', 'Troca de Roupa de Cama')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quote',
            name='best_day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quote',
            name='living_addon',
            field=models.CharField(choices=[('a', 'Tirar pó dos armários'), ('b', 'Limpeza interna dos armários'), ('c', 'Limpeza de pia e box')], max_length=100),
        ),
    ]
