# Generated by Django 4.0.3 on 2022-04-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getservice', '0004_alter_quote_bedroom_addon_alter_quote_best_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='question_text',
        ),
        migrations.AddField(
            model_name='quote',
            name='observations',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
